POST http://localhost:3333/events
Content-Type: application/json
  
{
    "title": "Novo evento2",
    "details": null,
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/37c8743f-ed7f-480e-8464-0b04ba9275ff/attendees
Content-Type: application/json
  
{
  "name": "Bruno Patez",
  "email": "brunoapatez2@gmail.com"
}

###

GET http://localhost:3333/events/37c8743f-ed7f-480e-8464-0b04ba9275ff

###

GET http://localhost:3333/attendees/2/badge

###

GET http://localhost:3333/attendees/4/check-in

###

GET http://localhost:3333/events/37c8743f-ed7f-480e-8464-0b04ba9275ff/attendees